### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by Jppx** [linux-rockchip/linux-rockchip#1]
Hi - I don't know if development on this project is finished. But I'm getting a compilation error with the rk3288 version.

  CC      drivers/usb/dwc_otg_310/dwc_otg_hcd.o
drivers/usb/dwc_otg_310/dwc_otg_hcd.c: In function 'dwc_otg_hcd_rem_wakeup_cb':
drivers/usb/dwc_otg_310/dwc_otg_hcd.c:447:31: error: inlining failed in call to always_inline 'dwc_otg_hcd_to_hcd': function body not available
 extern inline struct usb_hcd _dwc_otg_hcd_to_hcd(dwc_otg_hcd_t *dwc_otg_hcd);
                               ^
drivers/usb/dwc_otg_310/dwc_otg_hcd.c:451:18: error: called from here
  struct usb_hcd *hcd = dwc_otg_hcd_to_hcd(dwc_otg_hcd);
                  ^
scripts/Makefile.build:308: recipe for target 'drivers/usb/dwc_otg_310/dwc_otg_hcd.o' failed
make[3]: *_\* [drivers/usb/dwc_otg_310/dwc_otg_hcd.o] Error 1
scripts/Makefile.build:455: recipe for target 'drivers/usb/dwc_otg_310' failed
make[2]: **\* [drivers/usb/dwc_otg_310] Error 2
scripts/Makefile.build:455: recipe for target 'drivers/usb' failed
make[1]: **\* [drivers/usb] Error 2
Makefile:812: recipe for target 'drivers' failed

It is the current state of the kernel source?

Regards,

Jppx

**Comment by ghost** [comment]
this is just a mirror. there is no project.
anyway, you can use source code freely.
